### PR TITLE
Build for windows

### PR DESCRIPTION
**Pull request by PrimozGodec**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by PrimozGodec** [comment]
After freetds is ready for Windows also pymssql should support it. @mariusvniekerk I think it is ready. After merging this one, I can try to work on newer versions.

**Comment by maresb** [comment]
Closes #1 and closes #15

**Comment by PrimozGodec** [comment]
@conda-forge/pymssql or @conda-forge/core can someone check this and merge it?
Sorry for pushing but I would really like this to be merged to continue work on the other repository which depends on it.

**Comment by dopplershift** [comment]
@PrimozGodec I would suggest adding yourself as a maintainer for this recipe [following our documentation](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username) so that you can handle such upgrades if the recipe is in your critical path.

(I'll leave this to @mariusvniekerk for now.)

**Comment by PrimozGodec** [comment]
@dopplershift, thanks for response. I initiated #33

**Pull request merged**
